#!/bin/bash

# OWASP Dependency Check Setup Guide
# Complete instructions for setting up and using OWASP Dependency Check

echo "🔍 OWASP Dependency Check Setup Guide"
echo "====================================="
echo ""

# Overview
echo "📋 OVERVIEW"
echo "==========="
echo ""
echo "OWASP Dependency Check (SCA - Software Composition Analysis):"
echo "  • Scans project dependencies for known vulnerabilities"
echo "  • Identifies outdated libraries"
echo "  • Detects CVEs (Common Vulnerabilities and Exposures)"
echo "  • Generates detailed reports"
echo "  • Integrates with CI/CD pipelines"
echo ""

# What it detects
echo "🎯 WHAT IT DETECTS"
echo "=================="
echo ""
echo "1. Known Vulnerabilities (CVEs)"
echo "   • Identifies packages with published CVEs"
echo "   • Provides severity ratings (Critical, High, Medium, Low)"
echo "   • Links to vulnerability details"
echo ""
echo "2. Outdated Libraries"
echo "   • Detects packages with newer versions available"
echo "   • Identifies deprecated packages"
echo "   • Suggests updates"
echo ""
echo "3. License Issues"
echo "   • Identifies problematic licenses"
echo "   • Checks license compatibility"
echo "   • Flags GPL and other restrictive licenses"
echo ""
echo "4. Security Advisories"
echo "   • Checks against multiple vulnerability databases"
echo "   • Includes NVD, npm, and other sources"
echo "   • Updates regularly"
echo ""

# Prerequisites
echo "📦 PREREQUISITES"
echo "================"
echo ""
echo "Required:"
echo "  ✓ Docker installed (for running Dependency Check)"
echo "  ✓ Node.js 14+ installed"
echo "  ✓ npm installed"
echo ""
echo "Optional:"
echo "  ✓ Dependency Check CLI (standalone)"
echo "  ✓ Java 8+ (for standalone version)"
echo ""

# Quick Start
echo "🚀 QUICK START"
echo "=============="
echo ""
echo "Option 1: Using npm (Recommended)"
echo "  npm run dependency-check"
echo ""
echo "Option 2: Using Docker directly"
echo "  npm run dependency-check:docker"
echo ""
echo "Option 3: Using npm audit (built-in)"
echo "  npm audit"
echo ""
echo "Option 4: Full security scan"
echo "  npm run full-scan"
echo ""

# Installation
echo "📥 INSTALLATION"
echo "==============="
echo ""
echo "Option A: Docker (Recommended)"
echo "  1. Install Docker: https://www.docker.com/products/docker-desktop"
echo "  2. Docker image: owasp/dependency-check"
echo "  3. Automatically downloaded on first run"
echo ""
echo "Option B: Standalone CLI"
echo "  1. Download: https://github.com/jeremylong/DependencyCheck_Home/releases"
echo "  2. Extract to /opt/dependency-check"
echo "  3. Add to PATH"
echo ""
echo "Option C: npm package"
echo "  npm install -g dependency-check"
echo ""

# Usage
echo "💻 USAGE"
echo "========"
echo ""
echo "npm Scripts:"
echo "  npm run security-check          - npm audit only"
echo "  npm run dependency-check        - Full Dependency Check"
echo "  npm run dependency-check:docker - Docker version"
echo "  npm run security-scan           - npm audit + Dependency Check"
echo "  npm run full-scan               - Lint + Audit + SonarQube + Dependency Check"
echo ""
echo "Docker Command:"
echo "  docker run --rm \\
echo "    -v \$(pwd):/src \\
echo "    owasp/dependency-check \\
echo "    --scan /src \\
echo "    --format JSON \\
echo "    --format HTML"
echo ""
echo "npm audit:"
echo "  npm audit                       - Show vulnerabilities"
echo "  npm audit fix                   - Auto-fix vulnerabilities"
echo "  npm audit fix --force           - Force fix (may break compatibility)"
echo ""

# Output
echo "📊 OUTPUT"
echo "========="
echo ""
echo "Reports generated in: ./reports/"
echo ""
echo "Formats:"
echo "  • JSON - Machine readable"
echo "  • HTML - Human readable"
echo "  • XML - Integration with tools"
echo "  • CSV - Spreadsheet compatible"
echo ""
echo "Report Contents:"
echo "  • Vulnerable dependencies"
echo "  • CVE details and links"
echo "  • Severity ratings"
echo "  • Remediation suggestions"
echo "  • License information"
echo ""

# Interpreting Results
echo "📈 INTERPRETING RESULTS"
echo "======================="
echo ""
echo "Severity Levels:"
echo "  🔴 CRITICAL - Immediate action required"
echo "  🟠 HIGH     - Should be fixed soon"
echo "  🟡 MEDIUM   - Plan to fix"
echo "  🟢 LOW      - Monitor and update when possible"
echo ""
echo "Actions:"
echo "  1. Review each vulnerability"
echo "  2. Check if package is actually used"
echo "  3. Update to patched version if available"
echo "  4. If no patch, consider alternative package"
echo "  5. Document exceptions if necessary"
echo ""

# Fixing Vulnerabilities
echo "🔧 FIXING VULNERABILITIES"
echo "========================="
echo ""
echo "Step 1: Identify vulnerable packages"
echo "  npm audit"
echo ""
echo "Step 2: Check for updates"
echo "  npm outdated"
echo ""
echo "Step 3: Update packages"
echo "  npm update package-name"
echo "  npm install package-name@latest"
echo ""
echo "Step 4: Auto-fix (use with caution)"
echo "  npm audit fix"
echo ""
echo "Step 5: Re-scan"
echo "  npm audit"
echo "  npm run dependency-check"
echo ""

# GitHub Actions Integration
echo "🔄 GITHUB ACTIONS INTEGRATION"
echo "============================="
echo ""
echo "Workflow file: .github/workflows/security-scan.yml"
echo ""
echo "Features:"
echo "  ✅ Runs on push and pull requests"
echo "  ✅ Scheduled daily scans"
echo "  ✅ Fails on critical vulnerabilities"
echo "  ✅ Comments results on PRs"
echo "  ✅ Uploads reports as artifacts"
echo ""
echo "Configuration:"
echo "  • Triggers: push, pull_request, schedule"
echo "  • Branches: main, master, develop"
echo "  • Schedule: Daily at 2 AM UTC"
echo ""

# Best Practices
echo "✅ BEST PRACTICES"
echo "================="
echo ""
echo "1. Regular Scanning"
echo "   • Run before each commit"
echo "   • Include in CI/CD pipeline"
echo "   • Schedule daily scans"
echo ""
echo "2. Keep Dependencies Updated"
echo "   • Check for updates regularly"
echo "   • Update non-breaking changes immediately"
echo "   • Test before deploying"
echo ""
echo "3. Review Vulnerabilities"
echo "   • Understand each vulnerability"
echo "   • Check if package is actually used"
echo "   • Prioritize by severity"
echo ""
echo "4. Document Exceptions"
echo "   • Explain why vulnerability is accepted"
echo "   • Set expiration date for exceptions"
echo "   • Review periodically"
echo ""
echo "5. Monitor Advisories"
echo "   • Subscribe to security advisories"
echo "   • Follow package maintainers"
echo "   • Join security mailing lists"
echo ""

# Troubleshooting
echo "🔧 TROUBLESHOOTING"
echo "=================="
echo ""
echo "Docker not found:"
echo "  1. Install Docker Desktop"
echo "  2. Verify: docker --version"
echo "  3. Start Docker daemon"
echo ""
echo "Scan takes too long:"
echo "  1. First run downloads database (~500MB)"
echo "  2. Subsequent runs are faster"
echo "  3. Use --exclude to skip directories"
echo ""
echo "False positives:"
echo "  1. Check CVE details"
echo "  2. Verify if package is vulnerable"
echo "  3. Check if vulnerability applies to your usage"
echo "  4. Document exceptions"
echo ""
echo "Memory issues:"
echo "  1. Increase Docker memory: docker run -m 4g"
echo "  2. Use --exclude to reduce scope"
echo "  3. Run on larger machine"
echo ""

# Expected Findings
echo "🎯 EXPECTED FINDINGS FOR VULNERABLE APP"
echo "========================================"
echo ""
echo "This project intentionally includes:"
echo "  • lodash 3.10.1 (vulnerable version)"
echo "  • Old dependencies with known CVEs"
echo "  • Outdated packages"
echo ""
echo "Expected vulnerabilities:"
echo "  • Multiple CVEs in lodash"
echo "  • Prototype pollution issues"
echo "  • Dependency chain vulnerabilities"
echo ""
echo "This is intentional for educational purposes!"
echo ""

# Resources
echo "📚 RESOURCES"
echo "============"
echo ""
echo "Documentation:"
echo "  • OWASP Dependency Check: https://owasp.org/www-project-dependency-check/"
echo "  • GitHub: https://github.com/jeremylong/DependencyCheck_Home"
echo "  • NVD Database: https://nvd.nist.gov/"
echo ""
echo "Vulnerability Databases:"
echo "  • NVD (National Vulnerability Database)"
echo "  • npm Security Advisories"
echo "  • GitHub Security Advisories"
echo "  • CVE Details"
echo ""
echo "Related Tools:"
echo "  • npm audit - Built-in npm vulnerability scanner"
echo "  • Snyk - Continuous vulnerability scanning"
echo "  • WhiteSource - Software composition analysis"
echo "  • Black Duck - Enterprise SCA"
echo ""

# Next Steps
echo "🚀 NEXT STEPS"
echo "============="
echo ""
echo "1. Run initial scan"
echo "   npm run dependency-check"
echo ""
echo "2. Review results"
echo "   Open reports/dependency-check-report.html"
echo ""
echo "3. Fix vulnerabilities"
echo "   npm audit fix"
echo ""
echo "4. Re-scan"
echo "   npm run dependency-check"
echo ""
echo "5. Integrate with GitHub"
echo "   Push to GitHub to trigger workflow"
echo ""
echo "6. Monitor regularly"
echo "   Set up scheduled scans"
echo ""

# Summary
echo "✅ SETUP COMPLETE"
echo "================="
echo ""
echo "You now have:"
echo "  ✓ OWASP Dependency Check configured"
echo "  ✓ npm audit enabled"
echo "  ✓ GitHub Actions workflow"
echo "  ✓ Docker integration"
echo "  ✓ npm scripts for easy scanning"
echo ""
echo "Start scanning:"
echo "  npm run dependency-check"
echo ""
