#!/bin/bash

# Gitleaks Setup Guide
# Complete instructions for setting up and using Gitleaks for secrets scanning

echo "🔐 Gitleaks Setup Guide"
echo "======================="
echo ""

# Overview
echo "📋 OVERVIEW"
echo "==========="
echo ""
echo "Gitleaks - Secrets Detection:"
echo "  • Scans git history for secrets"
echo "  • Detects API keys, tokens, passwords"
echo "  • Prevents accidental commits"
echo "  • Integrates with CI/CD pipelines"
echo "  • Supports custom patterns"
echo ""

# What it detects
echo "🎯 WHAT IT DETECTS"
echo "=================="
echo ""
echo "API Keys & Tokens:"
echo "  • AWS Access Keys"
echo "  • GitHub Tokens"
echo "  • Slack Webhooks"
echo "  • API Keys (generic)"
echo "  • OAuth tokens"
echo ""
echo "Database Credentials:"
echo "  • Database connection strings"
echo "  • MongoDB URIs"
echo "  • PostgreSQL credentials"
echo "  • MySQL passwords"
echo ""
echo "Cloud Credentials:"
echo "  • AWS credentials"
echo "  • Azure credentials"
echo "  • GCP credentials"
echo "  • SSH keys"
echo ""
echo "Private Keys:"
echo "  • RSA private keys"
echo "  • DSA private keys"
echo "  • EC private keys"
echo "  • PGP private keys"
echo ""
echo "Other Secrets:"
echo "  • Passwords"
echo "  • Encryption keys"
echo "  • JWT tokens"
echo "  • Certificates"
echo ""

# Prerequisites
echo "📦 PREREQUISITES"
echo "================"
echo ""
echo "Required:"
echo "  ✓ Git installed"
echo "  ✓ GitHub account (for Actions)"
echo ""
echo "Optional:"
echo "  ✓ Docker (for local scanning)"
echo "  ✓ Go 1.16+ (for building from source)"
echo ""

# Quick Start
echo "🚀 QUICK START"
echo "=============="
echo ""
echo "GitHub Actions (Recommended):"
echo "  • Workflow: .github/workflows/complete-security-scan.yml"
echo "  • Runs on: push, pull_request"
echo "  • Automatic: No setup needed"
echo ""
echo "Local Scanning:"
echo "  1. Install: brew install gitleaks (Mac)"
echo "  2. Scan: gitleaks detect --source . -v"
echo "  3. Review: Check for secrets"
echo ""

# Installation
echo "📥 INSTALLATION"
echo "==============="
echo ""
echo "Option A: GitHub Actions (Built-in)"
echo "  • No installation needed"
echo "  • Runs automatically on push/PR"
echo "  • Integrated in workflow"
echo ""
echo "Option B: Homebrew (Mac)"
echo "  brew install gitleaks"
echo ""
echo "Option C: Docker"
echo "  docker run zricethezav/gitleaks:latest detect --source ."
echo ""
echo "Option D: Binary Download"
echo "  https://github.com/gitleaks/gitleaks/releases"
echo ""
echo "Option E: Build from Source"
echo "  git clone https://github.com/gitleaks/gitleaks.git"
echo "  cd gitleaks"
echo "  make build"
echo ""

# Usage
echo "💻 USAGE"
echo "========"
echo ""
echo "GitHub Actions:"
echo "  • Automatic on push/PR"
echo "  • Results in PR comments"
echo "  • Fails on secrets found"
echo ""
echo "Local Scanning:"
echo "  gitleaks detect --source . -v"
echo "  gitleaks detect --source . --report-path report.json"
echo "  gitleaks detect --source . --report-format json"
echo ""
echo "Pre-commit Hook:"
echo "  gitleaks protect --source . --staged"
echo ""

# Configuration
echo "⚙️ CONFIGURATION"
echo "================"
echo ""
echo "Default Rules:"
echo "  • AWS credentials"
echo "  • GitHub tokens"
echo "  • Slack webhooks"
echo "  • Private keys"
echo "  • Database credentials"
echo ""
echo "Custom Rules:"
echo "  Create .gitleaks.toml"
echo "  Define custom patterns"
echo "  Exclude false positives"
echo ""

# Output
echo "📊 OUTPUT"
echo "========="
echo ""
echo "Report Formats:"
echo "  • JSON - Machine readable"
echo "  • SARIF - Security Analysis Results Format"
echo "  • CSV - Spreadsheet compatible"
echo ""
echo "Report Contents:"
echo "  • Secret type"
echo "  • File location"
echo "  • Line number"
echo "  • Matched pattern"
echo "  • Severity"
echo ""

# Interpreting Results
echo "📈 INTERPRETING RESULTS"
echo "======================="
echo ""
echo "If secrets found:"
echo "  1. Immediately revoke the secret"
echo "  2. Remove from git history"
echo "  3. Use git-filter-repo to clean history"
echo "  4. Force push (if safe)"
echo "  5. Rotate credentials"
echo ""
echo "False Positives:"
echo "  1. Review the match"
echo "  2. Add to .gitleaks.toml allowlist"
echo "  3. Use --allow-list flag"
echo "  4. Document the exception"
echo ""

# Fixing Secrets
echo "🔧 FIXING SECRETS"
echo "================="
echo ""
echo "Step 1: Identify the secret"
echo "  • Note file and line number"
echo "  • Understand what was exposed"
echo ""
echo "Step 2: Revoke immediately"
echo "  • Rotate API keys"
echo "  • Reset passwords"
echo "  • Revoke tokens"
echo ""
echo "Step 3: Remove from history"
echo "  Option A: git-filter-repo"
echo "    git filter-repo --invert-paths --path <file>"
echo ""
echo "  Option B: BFG Repo-Cleaner"
echo "    bfg --delete-files <file>"
echo ""
echo "Step 4: Force push"
echo "  git push --force-with-lease"
echo ""
echo "Step 5: Notify team"
echo "  • Inform about exposure"
echo "  • Share remediation steps"
echo ""

# GitHub Actions Integration
echo "🔄 GITHUB ACTIONS INTEGRATION"
echo "============================="
echo ""
echo "Workflow file: .github/workflows/complete-security-scan.yml"
echo ""
echo "Features:"
echo "  ✅ Runs on push and pull requests"
echo "  ✅ Scans entire git history"
echo "  ✅ Fails pipeline if secrets found"
echo "  ✅ Comments on PRs with results"
echo "  ✅ Uploads SARIF report"
echo ""
echo "Configuration:"
echo "  • Triggers: push, pull_request, schedule"
echo "  • Branches: main, master, develop"
echo "  • Schedule: Daily at 2 AM UTC"
echo ""

# Best Practices
echo "✅ BEST PRACTICES"
echo "================="
echo ""
echo "1. Prevention"
echo "   • Use environment variables"
echo "   • Never commit secrets"
echo "   • Use .gitignore for config files"
echo "   • Use secret management tools"
echo ""
echo "2. Detection"
echo "   • Run Gitleaks before commit"
echo "   • Use pre-commit hooks"
echo "   • Scan in CI/CD pipeline"
echo "   • Regular history scans"
echo ""
echo "3. Response"
echo "   • Immediately revoke secrets"
echo "   • Remove from git history"
echo "   • Notify team"
echo "   • Update security policies"
echo ""
echo "4. Prevention Tools"
echo "   • AWS Secrets Manager"
echo "   • HashiCorp Vault"
echo "   • GitHub Secrets"
echo "   • Environment variables"
echo ""

# Pre-commit Hook
echo "🪝 PRE-COMMIT HOOK"
echo "=================="
echo ""
echo "Setup:"
echo "  1. Create .git/hooks/pre-commit"
echo "  2. Add: gitleaks protect --source . --staged"
echo "  3. Make executable: chmod +x .git/hooks/pre-commit"
echo ""
echo "Usage:"
echo "  • Runs before each commit"
echo "  • Prevents committing secrets"
echo "  • Can be bypassed with --no-verify"
echo ""

# Troubleshooting
echo "🔧 TROUBLESHOOTING"
echo "=================="
echo ""
echo "False positives:"
echo "  1. Review the match"
echo "  2. Add to allowlist in .gitleaks.toml"
echo "  3. Use --allow-list flag"
echo ""
echo "Scan takes too long:"
echo "  1. Limit history: --max-depth 100"
echo "  2. Scan only staged: --staged"
echo "  3. Exclude large files"
echo ""
echo "Secrets not detected:"
echo "  1. Check pattern matches"
echo "  2. Enable verbose: -v"
echo "  3. Add custom rules"
echo ""

# Expected Findings
echo "🎯 EXPECTED FINDINGS"
echo "===================="
echo ""
echo "For this vulnerable app:"
echo "  • Hardcoded API key in server.js"
echo "  • Secret token in server.js"
echo "  • Test credentials in comments"
echo ""
echo "This is intentional for educational purposes!"
echo ""

# Resources
echo "📚 RESOURCES"
echo "============"
echo ""
echo "Documentation:"
echo "  • Gitleaks: https://github.com/gitleaks/gitleaks"
echo "  • Rules: https://github.com/gitleaks/gitleaks/tree/master/cmd/generate/config/rules"
echo ""
echo "Related Tools:"
echo "  • git-secrets - AWS tool"
echo "  • TruffleHog - Secret scanning"
echo "  • detect-secrets - Yelp tool"
echo ""

# Next Steps
echo "🚀 NEXT STEPS"
echo "============="
echo ""
echo "1. Review workflow"
echo "   .github/workflows/complete-security-scan.yml"
echo ""
echo "2. Push to GitHub"
echo "   Workflow runs automatically"
echo ""
echo "3. Check results"
echo "   View PR comments"
echo "   Download SARIF report"
echo ""
echo "4. Fix any secrets"
echo "   Revoke immediately"
echo "   Remove from history"
echo ""
echo "5. Set up pre-commit hook"
echo "   Prevent future leaks"
echo ""

# Summary
echo "✅ SETUP COMPLETE"
echo "================="
echo ""
echo "You now have:"
echo "  ✓ Gitleaks integrated in GitHub Actions"
echo "  ✓ Automatic secrets scanning"
echo "  ✓ PR comments with results"
echo "  ✓ SARIF report generation"
echo "  ✓ Pipeline failure on secrets"
echo ""
echo "Start using:"
echo "  git push  # Workflow runs automatically"
echo ""
