#!/bin/bash

# IAM Hardening & AWS Security Setup Guide
# Complete instructions for securing AWS deployments

echo "🔐 IAM Hardening & AWS Security Setup"
echo "====================================="
echo ""

# Overview
echo "📋 OVERVIEW"
echo "==========="
echo ""
echo "AWS IAM Security Best Practices:"
echo "  • Never use root account"
echo "  • Use IAM roles instead of access keys"
echo "  • Implement least privilege principle"
echo "  • Enable MFA on all accounts"
echo "  • Rotate credentials regularly"
echo "  • Use temporary credentials"
echo "  • Monitor and audit access"
echo ""

# Root Account Security
echo "🚨 ROOT ACCOUNT SECURITY"
echo "======================="
echo ""
echo "NEVER use root account for:"
echo "  ❌ Daily operations"
echo "  ❌ Application deployments"
echo "  ❌ CI/CD pipelines"
echo "  ❌ Development work"
echo ""
echo "Root account should ONLY be used for:"
echo "  ✅ Initial AWS account setup"
echo "  ✅ Billing management"
echo "  ✅ Account recovery"
echo ""
echo "Secure root account:"
echo "  1. Enable MFA on root account"
echo "  2. Create strong password"
echo "  3. Store credentials securely"
echo "  4. Never share root credentials"
echo "  5. Disable root access keys"
echo ""

# IAM Users vs Roles
echo "👤 IAM USERS vs ROLES"
echo "===================="
echo ""
echo "IAM Users (for people):"
echo "  • Long-term credentials"
echo "  • Username and password"
echo "  • Access keys (if needed)"
echo "  • Use case: Human users"
echo ""
echo "IAM Roles (for services):"
echo "  • Temporary credentials"
echo "  • Automatically rotated"
echo "  • No long-term secrets"
echo "  • Use case: EC2, Lambda, ECS, etc."
echo ""
echo "Best Practice:"
echo "  ✅ Use IAM Roles for applications"
echo "  ✅ Use IAM Users for people (with MFA)"
echo "  ❌ Never use access keys in code"
echo "  ❌ Never hardcode credentials"
echo ""

# Least Privilege Principle
echo "🔒 LEAST PRIVILEGE PRINCIPLE"
echo "============================"
echo ""
echo "What is it?"
echo "  Grant only the minimum permissions needed"
echo "  Reduce attack surface"
echo "  Limit damage from compromised credentials"
echo ""
echo "Bad Policy (TOO PERMISSIVE):"
echo "  {\"Action\": \"*\", \"Resource\": \"*\"}"
echo "  • Grants all actions on all resources"
echo "  • Violates security best practices"
echo "  • High risk if credentials compromised"
echo ""
echo "Good Policy (LEAST PRIVILEGE):"
echo "  {"
echo "    \"Action\": ["
echo "      \"s3:GetObject\","
echo "      \"s3:PutObject\""
echo "    ],"
echo "    \"Resource\": \"arn:aws:s3:::my-bucket/*\""
echo "  }"
echo "  • Only allows specific actions"
echo "  • Only on specific resources"
echo "  • Minimal risk"
echo ""

# IAM Policy Examples
echo "📋 IAM POLICY EXAMPLES"
echo "====================="
echo ""
echo "Example 1: S3 Read-Only Access"
echo "  {"
echo "    \"Version\": \"2012-10-17\","
echo "    \"Statement\": ["
echo "      {"
echo "        \"Effect\": \"Allow\","
echo "        \"Action\": [\"s3:GetObject\"],"
echo "        \"Resource\": \"arn:aws:s3:::my-bucket/*\""
echo "      }"
echo "    ]"
echo "  }"
echo ""
echo "Example 2: EC2 Instance Management"
echo "  {"
echo "    \"Version\": \"2012-10-17\","
echo "    \"Statement\": ["
echo "      {"
echo "        \"Effect\": \"Allow\","
echo "        \"Action\": ["
echo "          \"ec2:StartInstances\","
echo "          \"ec2:StopInstances\","
echo "          \"ec2:DescribeInstances\""
echo "        ],"
echo "        \"Resource\": \"arn:aws:ec2:*:*:instance/*\","
echo "        \"Condition\": {"
echo "          \"StringEquals\": {\"aws:RequestedRegion\": \"us-east-1\"}"
echo "        }"
echo "      }"
echo "    ]"
echo "  }"
echo ""
echo "Example 3: Lambda Execution Role"
echo "  {"
echo "    \"Version\": \"2012-10-17\","
echo "    \"Statement\": ["
echo "      {"
echo "        \"Effect\": \"Allow\","
echo "        \"Action\": [\"logs:CreateLogGroup\", \"logs:CreateLogStream\"],"
echo "        \"Resource\": \"arn:aws:logs:*:*:*\""
echo "      },"
echo "      {"
echo "        \"Effect\": \"Allow\","
echo "        \"Action\": [\"s3:GetObject\"],"
echo "        \"Resource\": \"arn:aws:s3:::my-bucket/*\""
echo "      }"
echo "    ]"
echo "  }"
echo ""

# Credentials Management
echo "🔑 CREDENTIALS MANAGEMENT"
echo "========================="
echo ""
echo "NEVER do this:"
echo "  ❌ Hardcode AWS credentials in code"
echo "  ❌ Commit credentials to git"
echo "  ❌ Store credentials in environment files"
echo "  ❌ Share credentials via email/chat"
echo "  ❌ Use root account credentials"
echo "  ❌ Use long-term access keys"
echo ""
echo "DO this instead:"
echo "  ✅ Use IAM Roles (automatic credentials)"
echo "  ✅ Use AWS Secrets Manager"
echo "  ✅ Use AWS Systems Manager Parameter Store"
echo "  ✅ Use environment variables (from secure source)"
echo "  ✅ Use temporary credentials (STS)"
echo "  ✅ Rotate credentials regularly"
echo ""

# Environment Variables
echo "🌍 ENVIRONMENT VARIABLES"
echo "========================"
echo ""
echo "Secure way to pass credentials:"
echo ""
echo "1. Set in CI/CD system:"
echo "   GitHub Actions Secrets:"
echo "   - Settings → Secrets → New repository secret"
echo "   - Name: AWS_ACCESS_KEY_ID"
echo "   - Value: your-access-key"
echo ""
echo "2. Use in workflow:"
echo "   env:"
echo "     AWS_ACCESS_KEY_ID: \${{ secrets.AWS_ACCESS_KEY_ID }}"
echo "     AWS_SECRET_ACCESS_KEY: \${{ secrets.AWS_SECRET_ACCESS_KEY }}"
echo ""
echo "3. Access in code:"
echo "   const accessKey = process.env.AWS_ACCESS_KEY_ID;"
echo "   const secretKey = process.env.AWS_SECRET_ACCESS_KEY;"
echo ""
echo "4. Never log credentials:"
echo "   console.log(process.env.AWS_SECRET_ACCESS_KEY); // ❌ NEVER"
echo ""

# IAM Role for Deployment
echo "🚀 IAM ROLE FOR DEPLOYMENT"
echo "=========================="
echo ""
echo "Create IAM Role for GitHub Actions:"
echo ""
echo "1. Go to AWS IAM Console"
echo "2. Click 'Roles' → 'Create role'"
echo "3. Select 'Web identity'"
echo "4. Choose 'GitHub' as provider"
echo "5. Enter GitHub repository details"
echo "6. Attach policies (least privilege)"
echo "7. Create role"
echo ""
echo "Example Trust Policy:"
echo "  {"
echo "    \"Version\": \"2012-10-17\","
echo "    \"Statement\": ["
echo "      {"
echo "        \"Effect\": \"Allow\","
echo "        \"Principal\": {"
echo "          \"Federated\": \"arn:aws:iam::ACCOUNT_ID:oidc-provider/token.actions.githubusercontent.com\""
echo "        },"
echo "        \"Action\": \"sts:AssumeRoleWithWebIdentity\","
echo "        \"Condition\": {"
echo "          \"StringEquals\": {"
echo "            \"token.actions.githubusercontent.com:aud\": \"sts.amazonaws.com\","
echo "            \"token.actions.githubusercontent.com:sub\": \"repo:USERNAME/REPO:ref:refs/heads/main\""
echo "          }"
echo "        }"
echo "      }"
echo "    ]"
echo "  }"
echo ""

# GitHub Actions with IAM Role
echo "🔄 GITHUB ACTIONS WITH IAM ROLE"
echo "==============================="
echo ""
echo "Workflow example:"
echo ""
echo "name: Deploy with IAM Role"
echo "on: [push]"
echo ""
echo "jobs:"
echo "  deploy:"
echo "    runs-on: ubuntu-latest"
echo "    permissions:"
echo "      id-token: write"
echo "      contents: read"
echo ""
echo "    steps:"
echo "      - uses: actions/checkout@v3"
echo ""
echo "      - name: Configure AWS credentials"
echo "        uses: aws-actions/configure-aws-credentials@v2"
echo "        with:"
echo "          role-to-assume: arn:aws:iam::ACCOUNT_ID:role/GitHubActionsRole"
echo "          aws-region: us-east-1"
echo ""
echo "      - name: Deploy"
echo "        run: |"
echo "          aws s3 cp app.zip s3://my-bucket/"
echo "          aws lambda update-function-code --function-name my-function --s3-bucket my-bucket --s3-key app.zip"
echo ""

# MFA Setup
echo "🔐 MULTI-FACTOR AUTHENTICATION (MFA)"
echo "===================================="
echo ""
echo "Enable MFA for:"
echo "  ✅ Root account (REQUIRED)"
echo "  ✅ All IAM users"
echo "  ✅ Privileged accounts"
echo ""
echo "MFA Types:"
echo "  • Virtual MFA (Google Authenticator, Authy)"
echo "  • Hardware MFA (YubiKey)"
echo "  • SMS MFA (not recommended)"
echo ""
echo "Setup MFA:"
echo "  1. Go to AWS IAM Console"
echo "  2. Click 'Users' → Select user"
echo "  3. Click 'Security credentials' tab"
echo "  4. Click 'Assign MFA device'"
echo "  5. Choose MFA device type"
echo "  6. Follow setup instructions"
echo ""

# Access Keys Management
echo "🔑 ACCESS KEYS MANAGEMENT"
echo "========================="
echo ""
echo "When to use access keys:"
echo "  • Only when IAM Roles not available"
echo "  • For programmatic access"
echo "  • For local development (temporary)"
echo ""
echo "Best practices:"
echo "  ✅ Rotate every 90 days"
echo "  ✅ Use temporary credentials (STS)"
echo "  ✅ Store in secure location"
echo "  ✅ Never commit to git"
echo "  ✅ Use AWS Secrets Manager"
echo "  ✅ Monitor usage with CloudTrail"
echo ""
echo "Rotate access keys:"
echo "  1. Create new access key"
echo "  2. Update applications with new key"
echo "  3. Test thoroughly"
echo "  4. Deactivate old key"
echo "  5. Delete old key after 30 days"
echo ""

# Monitoring & Auditing
echo "📊 MONITORING & AUDITING"
echo "========================"
echo ""
echo "Enable CloudTrail:"
echo "  • Logs all API calls"
echo "  • Tracks who did what and when"
echo "  • Essential for security audits"
echo ""
echo "Enable CloudWatch:"
echo "  • Monitor metrics"
echo "  • Set up alarms"
echo "  • Track unusual activity"
echo ""
echo "Review IAM Access Analyzer:"
echo "  • Identifies unused permissions"
echo "  • Suggests least privilege policies"
echo "  • Validates policies"
echo ""
echo "Check AWS Config:"
echo "  • Tracks configuration changes"
echo "  • Compliance monitoring"
echo "  • Security best practices"
echo ""

# Security Checklist
echo "✅ SECURITY CHECKLIST"
echo "===================="
echo ""
echo "Account Setup:"
echo "  ☐ Enable MFA on root account"
echo "  ☐ Create IAM users for team members"
echo "  ☐ Enable MFA on all IAM users"
echo "  ☐ Disable root access keys"
echo ""
echo "IAM Configuration:"
echo "  ☐ Create IAM roles for applications"
echo "  ☐ Implement least privilege policies"
echo "  ☐ Review and remove unused permissions"
echo "  ☐ Use resource-based policies"
echo ""
echo "Credentials:"
echo "  ☐ Never hardcode credentials"
echo "  ☐ Use environment variables"
echo "  ☐ Use AWS Secrets Manager"
echo "  ☐ Rotate credentials regularly"
echo ""
echo "Monitoring:"
echo "  ☐ Enable CloudTrail"
echo "  ☐ Enable CloudWatch"
echo "  ☐ Set up alarms"
echo "  ☐ Review logs regularly"
echo ""
echo "CI/CD:"
echo "  ☐ Use IAM roles for deployments"
echo "  ☐ Store secrets in CI/CD system"
echo "  ☐ Never log credentials"
echo "  ☐ Audit deployment access"
echo ""

# Resources
echo "📚 RESOURCES"
echo "============"
echo ""
echo "AWS Documentation:"
echo "  • IAM Best Practices: https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html"
echo "  • IAM Policies: https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html"
echo "  • Security Best Practices: https://aws.amazon.com/architecture/security-identity-compliance/"
echo ""
echo "Tools:"
echo "  • AWS IAM Access Analyzer"
echo "  • AWS Config"
echo "  • CloudTrail"
echo "  • CloudWatch"
echo ""

# Next Steps
echo "🚀 NEXT STEPS"
echo "============="
echo ""
echo "1. Secure root account"
echo "   • Enable MFA"
echo "   • Create strong password"
echo ""
echo "2. Create IAM users"
echo "   • One per team member"
echo "   • Enable MFA"
echo ""
echo "3. Create IAM roles"
echo "   • For applications"
echo "   • For CI/CD"
echo "   • Least privilege policies"
echo ""
echo "4. Set up monitoring"
echo "   • Enable CloudTrail"
echo "   • Enable CloudWatch"
echo "   • Set up alarms"
echo ""
echo "5. Implement in CI/CD"
echo "   • Use IAM roles"
echo "   • Store secrets securely"
echo "   • Audit access"
echo ""

# Summary
echo "✅ IAM HARDENING COMPLETE"
echo "========================="
echo ""
echo "Key Takeaways:"
echo "  ✓ Never use root account"
echo "  ✓ Use IAM roles for applications"
echo "  ✓ Implement least privilege"
echo "  ✓ Never hardcode credentials"
echo "  ✓ Enable MFA everywhere"
echo "  ✓ Monitor and audit access"
echo ""
