#!/bin/bash

# SonarQube Setup Guide
# Complete instructions for setting up and using SonarQube with the vulnerable app

echo "🚀 SonarQube Setup Guide"
echo "======================="
echo ""

# Step 1: Prerequisites
echo "📋 STEP 1: Prerequisites"
echo "========================"
echo ""
echo "Required:"
echo "  ✓ Docker installed"
echo "  ✓ Docker Compose installed"
echo "  ✓ Node.js 14+ installed"
echo "  ✓ npm installed"
echo ""
echo "Check versions:"
echo "  docker --version"
echo "  docker-compose --version"
echo "  node --version"
echo "  npm --version"
echo ""

# Step 2: Quick Start
echo "🚀 STEP 2: Quick Start (5 minutes)"
echo "==================================="
echo ""
echo "Option A: Using Docker Compose (Recommended)"
echo "  1. docker-compose up -d"
echo "  2. Wait 30-60 seconds for SonarQube to start"
echo "  3. Open http://localhost:9000"
echo "  4. Login with admin/admin"
echo ""
echo "Option B: Using Setup Script"
echo "  Windows: setup-sonarqube.bat"
echo "  Linux/Mac: bash setup-sonarqube.sh"
echo ""
echo "Option C: Using Node.js Script"
echo "  npm run sonar:setup"
echo ""

# Step 3: Access SonarQube
echo "🌐 STEP 3: Access SonarQube"
echo "============================"
echo ""
echo "Dashboard: http://localhost:9000"
echo "Default Credentials:"
echo "  Username: admin"
echo "  Password: admin"
echo ""
echo "⚠️  Change password on first login!"
echo ""

# Step 4: Generate Token
echo "🔑 STEP 4: Generate Authentication Token"
echo "=========================================="
echo ""
echo "1. Go to http://localhost:9000"
echo "2. Click on your profile (top right)"
echo "3. Select 'My Account' → 'Security'"
echo "4. Click 'Generate Tokens'"
echo "5. Enter token name: 'vulnerable-app-token'"
echo "6. Click 'Generate'"
echo "7. Copy the token (you won't see it again!)"
echo ""
echo "Or use: bash sonarqube-ops.sh token"
echo ""

# Step 5: Run Scanner
echo "📊 STEP 5: Run SonarQube Scanner"
echo "=================================="
echo ""
echo "Option A: Using npm"
echo "  npm run sonar"
echo ""
echo "Option B: Using Operations Script"
echo "  Windows: sonarqube-ops.bat scan"
echo "  Linux/Mac: bash sonarqube-ops.sh scan"
echo ""
echo "Option C: Manual Scanner"
echo "  sonar-scanner \\"
echo "    -Dsonar.projectKey=vulnerable-app \\"
echo "    -Dsonar.sources=. \\"
echo "    -Dsonar.host.url=http://localhost:9000 \\"
echo "    -Dsonar.login=YOUR_TOKEN"
echo ""

# Step 6: View Results
echo "📈 STEP 6: View Analysis Results"
echo "=================================="
echo ""
echo "1. Go to http://localhost:9000/projects"
echo "2. Click on 'vulnerable-app' project"
echo "3. View:"
echo "   - Bugs"
echo "   - Vulnerabilities"
echo "   - Code Smells"
echo "   - Coverage"
echo "   - Duplications"
echo ""
echo "Or use: bash sonarqube-ops.sh status"
echo ""

# Step 7: GitHub Actions
echo "🔄 STEP 7: GitHub Actions Integration"
echo "======================================"
echo ""
echo "The workflow file is already configured:"
echo "  .github/workflows/sonarqube-scan.yml"
echo ""
echo "To use with GitHub:"
echo "  1. Push code to GitHub"
echo "  2. Set up SonarQube instance (cloud or self-hosted)"
echo "  3. Add secrets to GitHub:"
echo "     - SONAR_HOST_URL"
echo "     - SONAR_LOGIN (token)"
echo "  4. Update workflow with your settings"
echo "  5. Workflow runs on push and pull requests"
echo ""

# Step 8: Operations Commands
echo "⚙️  STEP 8: Operations Commands"
echo "==============================="
echo ""
echo "Windows:"
echo "  sonarqube-ops.bat start       - Start SonarQube"
echo "  sonarqube-ops.bat stop        - Stop SonarQube"
echo "  sonarqube-ops.bat restart     - Restart SonarQube"
echo "  sonarqube-ops.bat scan        - Run scanner"
echo "  sonarqube-ops.bat status      - Get project status"
echo "  sonarqube-ops.bat dashboard   - Open dashboard"
echo "  sonarqube-ops.bat logs        - View logs"
echo "  sonarqube-ops.bat cleanup     - Remove containers"
echo ""
echo "Linux/Mac:"
echo "  bash sonarqube-ops.sh start"
echo "  bash sonarqube-ops.sh stop"
echo "  bash sonarqube-ops.sh restart"
echo "  bash sonarqube-ops.sh scan"
echo "  bash sonarqube-ops.sh status"
echo "  bash sonarqube-ops.sh dashboard"
echo "  bash sonarqube-ops.sh logs"
echo "  bash sonarqube-ops.sh cleanup"
echo ""

# Step 9: npm Scripts
echo "📦 STEP 9: npm Scripts"
echo "======================"
echo ""
echo "npm run start              - Start vulnerable app"
echo "npm run dev                - Start with nodemon"
echo "npm run test               - Run vulnerability tests"
echo "npm run sonar              - Run SonarQube scanner"
echo "npm run sonar:setup        - Setup SonarQube"
echo "npm run lint               - Run ESLint"
echo "npm run security-check     - Check for vulnerabilities"
echo ""

# Step 10: Troubleshooting
echo "🔧 STEP 10: Troubleshooting"
echo "============================"
echo ""
echo "SonarQube won't start:"
echo "  1. Check Docker: docker ps"
echo "  2. View logs: docker logs sonarqube-vulnerable-app"
echo "  3. Check ports: netstat -an | grep 9000"
echo "  4. Restart: docker-compose restart"
echo ""
echo "Scanner fails:"
echo "  1. Ensure SonarQube is running"
echo "  2. Check token is valid"
echo "  3. Verify sonar-scanner is installed: sonar-scanner --version"
echo "  4. Check sonar-project.properties exists"
echo ""
echo "Quality Gate fails:"
echo "  1. Review issues in dashboard"
echo "  2. Fix critical issues first"
echo "  3. Re-run scanner"
echo ""

# Step 11: Configuration
echo "⚙️  STEP 11: Configuration Files"
echo "================================="
echo ""
echo "sonar-project.properties"
echo "  - Project configuration"
echo "  - Exclusions"
echo "  - Quality gate settings"
echo ""
echo "docker-compose.yml"
echo "  - SonarQube service"
echo "  - PostgreSQL database"
echo "  - Volumes and networking"
echo ""
echo ".github/workflows/sonarqube-scan.yml"
echo "  - GitHub Actions workflow"
echo "  - Runs on push and PR"
echo "  - Fails pipeline on critical issues"
echo ""

# Step 12: Best Practices
echo "✅ STEP 12: Best Practices"
echo "==========================="
echo ""
echo "1. Run scanner before committing"
echo "2. Fix critical issues immediately"
echo "3. Review code smells regularly"
echo "4. Maintain high test coverage"
echo "5. Keep dependencies updated"
echo "6. Use quality gates in CI/CD"
echo "7. Review security vulnerabilities"
echo "8. Document exclusions"
echo ""

# Step 13: Integration with CI/CD
echo "🔄 STEP 13: CI/CD Integration"
echo "=============================="
echo ""
echo "GitHub Actions:"
echo "  - Workflow: .github/workflows/sonarqube-scan.yml"
echo "  - Runs on: push, pull_request"
echo "  - Fails on: critical issues"
echo ""
echo "Local Pre-commit:"
echo "  1. Add to .git/hooks/pre-commit"
echo "  2. Run: npm run sonar"
echo "  3. Fail if issues found"
echo ""

# Step 14: Cleanup
echo "🗑️  STEP 14: Cleanup"
echo "===================="
echo ""
echo "Stop SonarQube:"
echo "  docker-compose down"
echo ""
echo "Remove volumes:"
echo "  docker-compose down -v"
echo ""
echo "Remove all:"
echo "  docker-compose down -v"
echo "  docker volume rm sonarqube_data sonarqube_extensions sonarqube_logs postgres_data"
echo ""

# Step 15: Resources
echo "📚 STEP 15: Resources"
echo "====================="
echo ""
echo "Documentation:"
echo "  - SonarQube: https://docs.sonarqube.org/"
echo "  - Scanner: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/"
echo "  - Quality Gates: https://docs.sonarqube.org/latest/user-guide/quality-gates/"
echo ""
echo "Project Files:"
echo "  - sonar-project.properties - Configuration"
echo "  - docker-compose.yml - Docker setup"
echo "  - .github/workflows/sonarqube-scan.yml - GitHub Actions"
echo "  - sonarqube-ops.sh - Operations (Linux/Mac)"
echo "  - sonarqube-ops.bat - Operations (Windows)"
echo ""

echo ""
echo "✅ Setup Complete!"
echo ""
echo "Next steps:"
echo "  1. Start SonarQube: docker-compose up -d"
echo "  2. Wait for startup (30-60 seconds)"
echo "  3. Open http://localhost:9000"
echo "  4. Generate token"
echo "  5. Run scanner: npm run sonar"
echo ""
