#!/bin/bash

# Trivy Setup Guide
# Complete instructions for setting up and using Trivy for container security scanning

echo "🐳 Trivy Container Security Setup Guide"
echo "========================================"
echo ""

# Overview
echo "📋 OVERVIEW"
echo "==========="
echo ""
echo "Trivy - Container & Filesystem Vulnerability Scanner:"
echo "  • Scans Docker images for vulnerabilities"
echo "  • Detects OS package vulnerabilities"
echo "  • Identifies application dependencies"
echo "  • Checks for misconfigurations"
echo "  • Integrates with CI/CD pipelines"
echo "  • Fast and accurate scanning"
echo ""

# What it detects
echo "🎯 WHAT IT DETECTS"
echo "=================="
echo ""
echo "OS Vulnerabilities:"
echo "  • Alpine Linux vulnerabilities"
echo "  • Debian/Ubuntu vulnerabilities"
echo "  • CentOS/RHEL vulnerabilities"
echo "  • Amazon Linux vulnerabilities"
echo "  • Other Linux distributions"
echo ""
echo "Application Dependencies:"
echo "  • npm packages"
echo "  • Python packages"
echo "  • Java dependencies"
echo "  • Ruby gems"
echo "  • Go modules"
echo "  • PHP packages"
echo ""
echo "Misconfigurations:"
echo "  • Dockerfile best practices"
echo "  • Kubernetes manifests"
echo "  • Terraform configurations"
echo "  • CloudFormation templates"
echo ""
echo "Secrets:"
echo "  • API keys"
echo "  • Passwords"
echo "  • Tokens"
echo "  • Private keys"
echo ""

# Prerequisites
echo "📦 PREREQUISITES"
echo "================"
echo ""
echo "Required:"
echo "  ✓ Docker installed (for scanning images)"
echo "  ✓ GitHub account (for Actions)"
echo ""
echo "Optional:"
echo "  ✓ Trivy CLI installed locally"
echo "  ✓ Kubernetes cluster (for runtime scanning)"
echo ""

# Quick Start
echo "🚀 QUICK START"
echo "=============="
echo ""
echo "GitHub Actions (Recommended):"
echo "  • Workflow: .github/workflows/full-security-pipeline.yml"
echo "  • Runs on: push, pull_request"
echo "  • Automatic: No setup needed"
echo ""
echo "Local Scanning:"
echo "  1. Install: brew install trivy (Mac)"
echo "  2. Scan image: trivy image vulnerable-app:latest"
echo "  3. Scan filesystem: trivy fs ."
echo ""

# Installation
echo "📥 INSTALLATION"
echo "==============="
echo ""
echo "Option A: GitHub Actions (Built-in)"
echo "  • No installation needed"
echo "  • Runs automatically on push/PR"
echo "  • Integrated in workflow"
echo ""
echo "Option B: Homebrew (Mac)"
echo "  brew install trivy"
echo ""
echo "Option C: Docker"
echo "  docker run aquasec/trivy image vulnerable-app:latest"
echo ""
echo "Option D: Binary Download"
echo "  https://github.com/aquasecurity/trivy/releases"
echo ""
echo "Option E: Build from Source"
echo "  git clone https://github.com/aquasecurity/trivy.git"
echo "  cd trivy"
echo "  make build"
echo ""

# Usage
echo "💻 USAGE"
echo "========"
echo ""
echo "GitHub Actions:"
echo "  • Automatic on push/PR"
echo "  • Results in PR comments"
echo "  • SARIF report uploaded to GitHub Security"
echo ""
echo "Local Image Scanning:"
echo "  trivy image vulnerable-app:latest"
echo "  trivy image --severity HIGH,CRITICAL vulnerable-app:latest"
echo "  trivy image --format json vulnerable-app:latest > report.json"
echo ""
echo "Local Filesystem Scanning:"
echo "  trivy fs ."
echo "  trivy fs --severity HIGH,CRITICAL ."
echo "  trivy fs --skip-dirs node_modules ."
echo ""
echo "Kubernetes Scanning:"
echo "  trivy k8s cluster"
echo "  trivy k8s namespace default"
echo ""

# Configuration
echo "⚙️ CONFIGURATION"
echo "================"
echo ""
echo "Severity Levels:"
echo "  • CRITICAL - Immediate action required"
echo "  • HIGH - Should be fixed soon"
echo "  • MEDIUM - Plan to fix"
echo "  • LOW - Monitor and update"
echo "  • UNKNOWN - Severity not determined"
echo ""
echo "Scan Types:"
echo "  • image - Docker/OCI images"
echo "  • fs - Filesystem"
echo "  • k8s - Kubernetes cluster"
echo "  • repo - Git repository"
echo ""
echo "Output Formats:"
echo "  • table - Human readable"
echo "  • json - Machine readable"
echo "  • sarif - Security Analysis Results Format"
echo "  • cyclonedx - CycloneDX format"
echo ""

# Output
echo "📊 OUTPUT"
echo "========="
echo ""
echo "Report Contents:"
echo "  • Vulnerability ID (CVE)"
echo "  • Package name and version"
echo "  • Severity rating"
echo "  • Description"
echo "  • Fixed version"
echo "  • References"
echo ""
echo "Report Formats:"
echo "  • JSON - Machine readable"
echo "  • SARIF - GitHub Security integration"
echo "  • Table - Human readable"
echo "  • CycloneDX - SBOM format"
echo ""

# Interpreting Results
echo "📈 INTERPRETING RESULTS"
echo "======================="
echo ""
echo "If vulnerabilities found:"
echo "  1. Review severity"
echo "  2. Check if package is used"
echo "  3. Update to patched version"
echo "  4. If no patch, consider alternative"
echo "  5. Document exceptions"
echo ""
echo "False Positives:"
echo "  1. Review the vulnerability"
echo "  2. Check if it applies to your usage"
echo "  3. Add to ignore list if needed"
echo "  4. Document the reason"
echo ""

# Fixing Vulnerabilities
echo "🔧 FIXING VULNERABILITIES"
echo "========================="
echo ""
echo "Step 1: Identify vulnerable package"
echo "  • Note package name and version"
echo "  • Check CVE details"
echo ""
echo "Step 2: Update package"
echo "  • Update to patched version"
echo "  • Test for compatibility"
echo "  • Rebuild Docker image"
echo ""
echo "Step 3: Rebuild image"
echo "  docker build -t vulnerable-app:latest ."
echo ""
echo "Step 4: Re-scan"
echo "  trivy image vulnerable-app:latest"
echo ""
echo "Step 5: Deploy"
echo "  • Push to registry"
echo "  • Deploy to production"
echo ""

# GitHub Actions Integration
echo "🔄 GITHUB ACTIONS INTEGRATION"
echo "============================="
echo ""
echo "Workflow file: .github/workflows/full-security-pipeline.yml"
echo ""
echo "Features:"
echo "  ✅ Scans Docker images"
echo "  ✅ Scans filesystem"
echo "  ✅ Generates SARIF reports"
echo "  ✅ Uploads to GitHub Security"
echo "  ✅ Comments on PRs with results"
echo "  ✅ Fails on critical vulnerabilities"
echo ""
echo "Configuration:"
echo "  • Triggers: push, pull_request, schedule"
echo "  • Branches: main, master, develop"
echo "  • Schedule: Daily at 2 AM UTC"
echo ""

# Dockerfile Best Practices
echo "📝 DOCKERFILE BEST PRACTICES"
echo "============================"
echo ""
echo "Use minimal base images:"
echo "  FROM alpine:latest"
echo "  FROM node:18-alpine"
echo "  FROM python:3.11-slim"
echo ""
echo "Keep images updated:"
echo "  RUN apk update && apk upgrade"
echo "  RUN apt-get update && apt-get upgrade"
echo ""
echo "Remove unnecessary packages:"
echo "  RUN apk del apk-tools"
echo "  RUN apt-get remove --purge"
echo ""
echo "Use specific versions:"
echo "  FROM node:18.16.0-alpine"
echo "  RUN npm install package@1.2.3"
echo ""
echo "Run as non-root:"
echo "  RUN useradd -m appuser"
echo "  USER appuser"
echo ""
echo "Scan regularly:"
echo "  • Before pushing to registry"
echo "  • In CI/CD pipeline"
echo "  • Scheduled daily scans"
echo ""

# Best Practices
echo "✅ BEST PRACTICES"
echo "================="
echo ""
echo "1. Regular Scanning"
echo "   • Scan before deployment"
echo "   • Include in CI/CD pipeline"
echo "   • Schedule daily scans"
echo ""
echo "2. Keep Base Images Updated"
echo "   • Use latest security patches"
echo "   • Monitor for updates"
echo "   • Rebuild regularly"
echo ""
echo "3. Minimize Attack Surface"
echo "   • Use minimal base images"
echo "   • Remove unnecessary packages"
echo "   • Run as non-root user"
echo ""
echo "4. Monitor Vulnerabilities"
echo "   • Subscribe to advisories"
echo "   • Follow security news"
echo "   • Review CVE databases"
echo ""
echo "5. Document Exceptions"
echo "   • Explain why vulnerability accepted"
echo "   • Set expiration date"
echo "   • Review periodically"
echo ""

# Troubleshooting
echo "🔧 TROUBLESHOOTING"
echo "=================="
echo ""
echo "Scan takes too long:"
echo "  1. First run downloads database (~500MB)"
echo "  2. Subsequent runs are faster"
echo "  3. Use --skip-dirs to exclude directories"
echo ""
echo "False positives:"
echo "  1. Review the vulnerability"
echo "  2. Check if it applies to your usage"
echo "  3. Add to ignore list if needed"
echo ""
echo "Image not found:"
echo "  1. Build image first: docker build -t vulnerable-app:latest ."
echo "  2. Check image name"
echo "  3. Verify Docker is running"
echo ""
echo "Permission denied:"
echo "  1. Run with sudo: sudo trivy image ..."
echo "  2. Add user to docker group"
echo "  3. Check Docker permissions"
echo ""

# Expected Findings
echo "🎯 EXPECTED FINDINGS"
echo "===================="
echo ""
echo "For this vulnerable app:"
echo "  • Node.js base image vulnerabilities"
echo "  • npm package vulnerabilities"
echo "  • OS package vulnerabilities"
echo "  • Outdated dependencies"
echo ""
echo "This is intentional for educational purposes!"
echo ""

# Resources
echo "📚 RESOURCES"
echo "============"
echo ""
echo "Documentation:"
echo "  • Trivy: https://aquasecurity.github.io/trivy/"
echo "  • GitHub: https://github.com/aquasecurity/trivy"
echo "  • Docs: https://aquasecurity.github.io/trivy/latest/"
echo ""
echo "Related Tools:"
echo "  • Grype - Vulnerability scanner"
echo "  • Clair - Container image scanning"
echo "  • Anchore - Container security"
echo ""

# Next Steps
echo "🚀 NEXT STEPS"
echo "============="
echo ""
echo "1. Create Dockerfile"
echo "   See Dockerfile in project root"
echo ""
echo "2. Build Docker image"
echo "   docker build -t vulnerable-app:latest ."
echo ""
echo "3. Scan locally"
echo "   trivy image vulnerable-app:latest"
echo ""
echo "4. Review results"
echo "   Check for vulnerabilities"
echo ""
echo "5. Push to GitHub"
echo "   Workflow runs automatically"
echo ""
echo "6. Monitor results"
echo "   Check PR comments"
echo "   Download SARIF report"
echo ""

# Summary
echo "✅ SETUP COMPLETE"
echo "================="
echo ""
echo "You now have:"
echo "  ✓ Trivy integrated in GitHub Actions"
echo "  ✓ Automatic container scanning"
echo "  ✓ Filesystem scanning"
echo "  ✓ SARIF report generation"
echo "  ✓ GitHub Security integration"
echo "  ✓ PR comments with results"
echo ""
echo "Start using:"
echo "  docker build -t vulnerable-app:latest ."
echo "  trivy image vulnerable-app:latest"
echo ""
